import { carImage } from "@/lib/car-images";
import type { Car } from "@/lib/types";

const images = (query: string) => [carImage(query), carImage(query, 1)];

export const seedCars = [
  {
    id: "seed-001",
    slug: "2018-toyota-camry-se",
    title: "2018 Toyota Camry SE",
    year: 2018,
    make: "Toyota",
    model: "Camry",
    trim: "SE",
    price: 13950,
    mileage: 84200,
    location: "Dallas, TX",
    transmission: "Automatic",
    drivetrain: "FWD",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    exteriorColor: "White",
    interiorColor: "Black cloth",
    vin: "4T1B11HK8JU000001",
    condition: "Good",
    engine: "2.5L I4",
    mpg: "28 city / 39 highway",
    images: images("Toyota Camry"),
    pills: ["Clean title", "Fuel saver", "New tires"],
    features: ["Bluetooth", "Backup camera", "Lane assist", "Sport seats"],
    description: "A dependable Camry SE with sharp styling, clean interior, and recent maintenance.",
    sold: false,
    createdAt: "2026-04-26T12:00:00.000Z",
  },
  {
    id: "seed-002",
    slug: "2016-honda-civic-ex",
    title: "2016 Honda Civic EX",
    year: 2016,
    make: "Honda",
    model: "Civic",
    trim: "EX",
    price: 11200,
    mileage: 105300,
    location: "Phoenix, AZ",
    transmission: "CVT Automatic",
    drivetrain: "FWD",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    exteriorColor: "White",
    interiorColor: "Gray cloth",
    vin: "19XFC2F79GE000002",
    condition: "Good",
    engine: "2.0L I4",
    mpg: "31 city / 41 highway",
    images: images("Honda Civic"),
    pills: ["Backup camera", "Great MPG", "Daily driver"],
    features: ["Sunroof", "Apple CarPlay", "Smart key", "Alloy wheels"],
    description: "Economical Civic EX with modern tech, roomy cabin, and strong service history.",
    sold: false,
    createdAt: "2026-04-24T12:00:00.000Z",
  },
  {
    id: "seed-003",
    slug: "2014-ford-f-150-xlt",
    title: "2014 Ford F-150 XLT",
    year: 2014,
    make: "Ford",
    model: "F-150",
    trim: "XLT",
    price: 14900,
    mileage: 132700,
    location: "Tampa, FL",
    transmission: "Automatic",
    drivetrain: "4WD",
    fuelType: "Gasoline",
    bodyType: "Truck",
    exteriorColor: "Oxford White",
    interiorColor: "Gray cloth",
    vin: "1FTFW1ET8EFA00003",
    condition: "Good",
    engine: "5.0L V8",
    mpg: "14 city / 19 highway",
    images: images("Ford F-150"),
    pills: ["4WD", "Tow package", "Work ready"],
    features: ["Crew cab", "Tow hitch", "Bed liner", "Power seat"],
    description: "Strong F-150 XLT crew cab with 4WD, tow equipment, and useful work-truck upgrades.",
    sold: false,
    createdAt: "2026-04-22T12:00:00.000Z",
  },
  {
    id: "seed-004",
    slug: "2017-chevrolet-malibu-lt",
    title: "2017 Chevrolet Malibu LT",
    year: 2017,
    make: "Chevrolet",
    model: "Malibu",
    trim: "LT",
    price: 9800,
    mileage: 118450,
    location: "Atlanta, GA",
    transmission: "Automatic",
    drivetrain: "FWD",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    exteriorColor: "Silver",
    interiorColor: "Jet black cloth",
    vin: "1G1ZE5ST7HF000004",
    condition: "Fair",
    engine: "1.5L Turbo I4",
    mpg: "27 city / 36 highway",
    images: images("Chevrolet Malibu"),
    pills: ["Cold AC", "Budget pick", "Minor dents"],
    features: ["Android Auto", "Backup camera", "Power driver seat", "Cruise control"],
    description: "Affordable Malibu LT with efficient turbo engine and normal cosmetic wear.",
    sold: false,
    createdAt: "2026-04-19T12:00:00.000Z",
  },
  {
    id: "seed-005",
    slug: "2015-nissan-altima-25-s",
    title: "2015 Nissan Altima 2.5 S",
    year: 2015,
    make: "Nissan",
    model: "Altima",
    trim: "2.5 S",
    price: 7400,
    mileage: 126900,
    location: "Charlotte, NC",
    transmission: "CVT Automatic",
    drivetrain: "FWD",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    exteriorColor: "Gray",
    interiorColor: "Black cloth",
    vin: "1N4AL3AP3FC000005",
    condition: "Fair",
    engine: "2.5L I4",
    mpg: "27 city / 38 highway",
    images: images("Nissan Altima"),
    pills: ["Low price", "Runs strong", "Cosmetic wear"],
    features: ["Keyless entry", "Bluetooth", "Power windows", "Cruise control"],
    description: "A practical Altima priced for a quick sale, with good fuel economy and clean cabin.",
    sold: false,
    createdAt: "2026-04-17T12:00:00.000Z",
  },
  {
    id: "seed-006",
    slug: "2019-hyundai-elantra-sel",
    title: "2019 Hyundai Elantra SEL",
    year: 2019,
    make: "Hyundai",
    model: "Elantra",
    trim: "SEL",
    price: 10850,
    mileage: 79300,
    location: "Las Vegas, NV",
    transmission: "Automatic",
    drivetrain: "FWD",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    exteriorColor: "White",
    interiorColor: "Black cloth",
    vin: "5NPD84LF3KH000006",
    condition: "Good",
    engine: "2.0L I4",
    mpg: "28 city / 37 highway",
    images: images("Hyundai Elantra"),
    pills: ["Blind spot alert", "Clean title", "Modern tech"],
    features: ["Apple CarPlay", "Lane keep assist", "Backup camera", "Heated mirrors"],
    description: "Clean Elantra SEL with driver assists, sharp styling, and comfortable daily manners.",
    sold: true,
    createdAt: "2026-04-15T12:00:00.000Z",
  },
  {
    id: "seed-007",
    slug: "2018-kia-soul-plus",
    title: "2018 Kia Soul Plus",
    year: 2018,
    make: "Kia",
    model: "Soul",
    trim: "Plus",
    price: 8950,
    mileage: 101800,
    location: "Columbus, OH",
    transmission: "Automatic",
    drivetrain: "FWD",
    fuelType: "Gasoline",
    bodyType: "Hatchback",
    exteriorColor: "White",
    interiorColor: "Black cloth",
    vin: "KNDJP3A50J7000007",
    condition: "Good",
    engine: "2.0L I4",
    mpg: "25 city / 30 highway",
    images: images("Kia Soul"),
    pills: ["Roomy hatch", "New brakes", "City friendly"],
    features: ["Backup camera", "Bluetooth", "Fold-flat seats", "USB audio"],
    description: "Compact outside, roomy inside, and easy to park. Great value city car.",
    sold: false,
    createdAt: "2026-04-12T12:00:00.000Z",
  },
  {
    id: "seed-008",
    slug: "2019-honda-cr-v-ex",
    title: "2019 Honda CR-V EX",
    year: 2019,
    make: "Honda",
    model: "CR-V",
    trim: "EX",
    price: 19800,
    mileage: 70400,
    location: "Richmond, VA",
    transmission: "CVT Automatic",
    drivetrain: "AWD",
    fuelType: "Gasoline",
    bodyType: "SUV",
    exteriorColor: "White",
    interiorColor: "Gray cloth",
    vin: "2HKRW2H53KH000021",
    condition: "Excellent",
    engine: "1.5L Turbo I4",
    mpg: "27 city / 33 highway",
    images: images("Honda CR-V"),
    pills: ["AWD", "Honda Sensing", "One owner"],
    features: ["Sunroof", "Adaptive cruise", "Heated seats", "Remote start"],
    description: "Excellent CR-V EX with AWD, Honda Sensing, and a versatile interior.",
    sold: false,
    createdAt: "2026-04-10T12:00:00.000Z",
  },
  {
    id: "seed-009",
    slug: "2021-nissan-leaf-sv",
    title: "2021 Nissan Leaf SV",
    year: 2021,
    make: "Nissan",
    model: "Leaf",
    trim: "SV",
    price: 15400,
    mileage: 38800,
    location: "Seattle, WA",
    transmission: "Single-speed",
    drivetrain: "FWD",
    fuelType: "Electric",
    bodyType: "Hatchback",
    exteriorColor: "White",
    interiorColor: "Black cloth",
    vin: "1N4AZ1CV4MC000024",
    condition: "Excellent",
    engine: "Electric motor",
    mpg: "149 mile EPA range",
    images: images("Nissan Leaf"),
    pills: ["EV", "Low miles", "City range"],
    features: ["ProPILOT assist", "Heated seats", "Navigation", "DC fast charge"],
    description: "Low-mile Leaf SV with driver assists, low operating costs, and excellent city usability.",
    sold: false,
    createdAt: "2026-04-08T12:00:00.000Z",
  },
  {
    id: "seed-010",
    slug: "2012-honda-accord-lx",
    title: "2012 Honda Accord LX",
    year: 2012,
    make: "Honda",
    model: "Accord",
    trim: "LX",
    price: 6500,
    mileage: 168200,
    location: "Memphis, TN",
    transmission: "Automatic",
    drivetrain: "FWD",
    fuelType: "Gasoline",
    bodyType: "Sedan",
    exteriorColor: "Silver",
    interiorColor: "Gray cloth",
    vin: "1HGCP2F30CA000023",
    condition: "Project",
    engine: "2.4L I4",
    mpg: "23 city / 34 highway",
    images: images("Honda Accord"),
    pills: ["Check engine light", "Runs", "Project car"],
    features: ["Power windows", "Cruise control", "Aux audio", "Large trunk"],
    description: "Accord project car that runs but needs diagnostic work for a check engine light.",
    sold: false,
    createdAt: "2026-04-06T12:00:00.000Z",
  },
  {
    id: "seed-011",
    slug: "2013-chevrolet-silverado-1500-lt",
    title: "2013 Chevrolet Silverado 1500 LT",
    year: 2013,
    make: "Chevrolet",
    model: "Silverado 1500",
    trim: "LT",
    price: 13500,
    mileage: 148800,
    location: "San Antonio, TX",
    transmission: "Automatic",
    drivetrain: "4WD",
    fuelType: "Gasoline",
    bodyType: "Truck",
    exteriorColor: "White",
    interiorColor: "Ebony cloth",
    vin: "3GCPCSE03DG000019",
    condition: "Fair",
    engine: "5.3L V8",
    mpg: "15 city / 21 highway",
    images: images("Chevrolet Silverado"),
    pills: ["V8", "Work truck", "Tow package"],
    features: ["Crew cab", "Tow hitch", "Bed liner", "Power locks"],
    description: "Straightforward Silverado LT with V8 power, 4WD utility, and practical work-truck equipment.",
    sold: false,
    createdAt: "2026-04-04T12:00:00.000Z",
  },
  {
    id: "seed-012",
    slug: "2018-ford-focus-se-hatchback",
    title: "2018 Ford Focus SE Hatchback",
    year: 2018,
    make: "Ford",
    model: "Focus",
    trim: "SE",
    price: 7600,
    mileage: 98200,
    location: "Kansas City, KS",
    transmission: "Automatic",
    drivetrain: "FWD",
    fuelType: "Gasoline",
    bodyType: "Hatchback",
    exteriorColor: "White",
    interiorColor: "Charcoal cloth",
    vin: "1FADP3K25JL000020",
    condition: "Mechanic Special",
    engine: "2.0L I4",
    mpg: "26 city / 38 highway",
    images: images("Ford Focus"),
    pills: ["Transmission shudder", "Mechanic special", "Runs and drives"],
    features: ["Backup camera", "Bluetooth", "Hatchback cargo", "USB audio"],
    description: "Budget Focus hatchback that runs and drives but has known transmission shudder.",
    sold: false,
    createdAt: "2026-04-02T12:00:00.000Z",
  },
] satisfies Car[];
